## 1.Vectors

In [1]:
import numpy as np


In [11]:
x1 = np.array([4,5,6])
print(x1)
print(x1.shape)
print(x1[0]) #acts as 1d

[4 5 6]
(3,)
4


In [14]:
# Represent vector as column vector having multiple rows
x = np.array([[4],[5],[6],[9]])
print(x)
print(x.shape)
print(x[0]) #acts as 2d so whole 0th row
print(x[0][0])

#Reshaping 
x = x.reshape(-1,2)
print(x)

[[4]
 [5]
 [6]
 [9]]
(4, 1)
[4]
4
[[4 5]
 [6 9]]


## 2.Matrices and Tensors

## 3.Transpose

In [15]:
print(x)
xt = np.transpose(x)
print(xt)

[[4 5]
 [6 9]]
[[4 6]
 [5 9]]


## Broadcasting

In [20]:
l = [1,2,3,4]
print(l)
# l=l+1 error

l = np.array(l) # lst to array
print(l)
l = l+1
print(l)

[1, 2, 3, 4, 5]
[1 2 3 4 5]
[2 3 4 5 6]


In [21]:
l1 = [[1,2,3,4],
     [5,6,7,8]]
print(l1)

l1 = np.array(l1)
print(l1)
l1 = l1+1
print(l1)

[[1, 2, 3, 4], [5, 6, 7, 8]]
[[1 2 3 4]
 [5 6 7 8]]
[[2 3 4 5]
 [6 7 8 9]]


## 5.Matrix Multiplication

In [24]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
Y = np.array([[10,20,30],[40,50,60],[70,80,90]])

print(X.shape,Y.shape)
print(X)
print(Y)

(3, 3) (3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [25]:
prod = np.dot(X,Y)
print(prod)

[[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]


## 6.Element wise Multiplication = Hadamard Product

In [26]:
print(X)
Y = np.eye(3)
print(Y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
print(X*Y)

[[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]


## 7.Norm

In [28]:
x = np.array([-5,2,10])

In [30]:
lp2 = np.linalg.norm(x) # by def order 2
print(lp2)

11.357816691600547


In [32]:
lp1 = np.linalg.norm(x,ord = 1)
print(lp1)

lpinf = np.linalg.norm(x,ord = np.inf)
print(lpinf)

17.0
10.0


In [35]:
b = np.array([[1,-1,2],
             [2,-1,-4],
             [1,-2,2]])
lpb = np.linalg.norm(b,ord = np.inf)
print(lpb)

7.0
